# Generated by Django 4.2.1 on 2023-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factcheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_input_news",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("fresult", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "gpt_check_result",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "sentiment_label",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
