# Generated by Django 4.2.1 on 2023-10-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="factcheck", name="url",),
        migrations.AddField(
            model_name="factcheck",
            name="genuine_urls",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="factcheck",
            name="non_authentic_urls",
            field=models.TextField(blank=True, null=True),
        ),
    ]
