# Generated by Django 4.2.1 on 2024-03-19 13:20

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_userreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="factcheck",
            name="genuine_urls_and_dates",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="factcheck",
            name="non_authentic_sources",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factcheck",
            name="num_genuine_sources",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factcheck",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="user_input_news",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="factcheck",
            name="genuine_urls",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="factcheck",
            name="non_authentic_urls",
            field=models.JSONField(default=list, null=True),
        ),
    ]
