# Generated by Django 4.2.1 on 2024-11-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_factcheck_genuine_urls_and_dates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factcheck",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
